### ISSUE TITLE
latest release do not have the port related changes in flask_eureka/eurekaclient.py

### ISSUE THREAD

**Issue by SomrajSeal** [elviejokike/flask-eureka#5]

**Comment by elviejokike** [comment]
Thanks @Somraj12345 . I have discovered some issues with our travis-ci. We will fix it as soon as I am back from holidays.

**Comment by SomrajSeal** [comment]
Thanks a ton.

**Comment by SomrajSeal** [comment]
Hi @elviejokike is the latest release 0.0.9 stable ?

**Comment by elviejokike** [comment]
Relase done: 0.1.0
